% -------------------------------------------------------------------
%  Generated by MATLAB on 8-Aug-2021 19:11:31
%  MATLAB version: 9.10.0.1602886 (R2021a)
% -------------------------------------------------------------------
                                                         

smiData = struct;
smiData.RigidTransform = struct;
smiData.RigidTransform(1).translation = ...
  [0 0 0];
smiData.RigidTransform(1).angle = 0;
smiData.RigidTransform(1).axis = [0 0 0];
smiData.RigidTransform(1).ID = 'B[Ball-1:-:Beam-1]';
smiData.RigidTransform(2).translation = ...
  [0.50000000000002842 35.002415458936355 -96.499999999999275];
smiData.RigidTransform(2).angle = 2.740170464104696;
smiData.RigidTransform(2).axis = [0.79204627467726962 -0.44517175147454957 ...
                                  -0.41771379012302312];
smiData.RigidTransform(2).ID = 'F[Ball-1:-:Beam-1]';
smiData.RigidTransform(3).translation = ...
  [0 0 0];
smiData.RigidTransform(3).angle = 0;
smiData.RigidTransform(3).axis = [0 0 0];
smiData.RigidTransform(3).ID = 'B[Ball-1:-:Support_E-1]';
smiData.RigidTransform(4).translation = ...
  [35.000000000000028 4.5048309178745622 1.0000000000011298];
smiData.RigidTransform(4).angle = 2.740170464104696;
smiData.RigidTransform(4).axis = [0.79204627467726962 -0.44517175147454952 ...
                                  -0.41771379012302312];
smiData.RigidTransform(4).ID = 'F[Ball-1:-:Support_E-1]';
smiData.RigidTransform(5).translation = ...
  [0 0 0];
smiData.RigidTransform(5).angle = 0;
smiData.RigidTransform(5).axis = [0 0 0];
smiData.RigidTransform(5).ID = 'B[Ball-1:-:Support_N-1]';
smiData.RigidTransform(6).translation = ...
  [0.50000000000001421 40.116373182290943 -31.499999999999631];
smiData.RigidTransform(6).angle = 2.740170464104696;
smiData.RigidTransform(6).axis = [0.79204627467726962 -0.44517175147454957 ...
                                  -0.41771379012302312];
smiData.RigidTransform(6).ID = 'F[Ball-1:-:Support_N-1]';
smiData.RigidTransform(7).translation = ...
  [0 0 150.00000000000003];
smiData.RigidTransform(7).angle = 1.1102230246251568E-16;
smiData.RigidTransform(7).axis = [1 0 0];
smiData.RigidTransform(7).ID = 'B[Base-1:-:]';
smiData.RigidTransform(8).translation = ...
  [-70.000000000000014 -2.8421709430404007E-14 -2.8421709430404007E-14];
smiData.RigidTransform(8).angle = 2.0943951023931957;
smiData.RigidTransform(8).axis = [0.57735026918962573 -0.57735026918962584 ...
                                  0.57735026918962573];
smiData.RigidTransform(8).ID = 'F[Base-1:-:]';
smiData.RigidTransform(9).translation = ...
  [-22.573593128807129 0 -14.999999999999986];
smiData.RigidTransform(9).angle = 2.0943951023931953;
smiData.RigidTransform(9).axis = [-0.57735026918962584 -0.57735026918962584 ...
                                  0.57735026918962584];
smiData.RigidTransform(9).ID = 'B[Base-1:-:Shaft-1]';
smiData.RigidTransform(10).translation = ...
  [-2.944957822825329E-14 1.193584102025848E-14 97.57359312880709];
smiData.RigidTransform(10).angle = 1.5700924586837754E-16;
smiData.RigidTransform(10).axis = [0.76043385655691642 -0.64941539079542532 ...
                                   -3.8768522813235515E-17];
smiData.RigidTransform(10).ID = 'F[Base-1:-:Shaft-1]';
smiData.RigidTransform(11).translation = ...
  [-2.244999999999969 -7.5010000000000217 78.494999999999933];
smiData.RigidTransform(11).angle = 0;
smiData.RigidTransform(11).axis = [0 0 0];
smiData.RigidTransform(11).ID = 'B[Shaft-1:-:Beam-1]';
smiData.RigidTransform(12).translation = ...
  [3.5000000000000373 2.2375845410619721 15.001000000000785];
smiData.RigidTransform(12).angle = 2.0943951023931957;
smiData.RigidTransform(12).axis = [-0.577350269189626 0.57735026918962562 ...
                                   -0.57735026918962562];
smiData.RigidTransform(12).ID = 'F[Shaft-1:-:Beam-1]';
smiData.RigidTransform(13).translation = ...
  [-5 -3.5024154589371745 -140];
smiData.RigidTransform(13).angle = 0;
smiData.RigidTransform(13).axis = [0 0 0];
smiData.RigidTransform(13).ID = 'B[Beam-1:-:Support_N-1]';
smiData.RigidTransform(14).translation = ...
  [-5.0000000000000284 1.6115422644174267 -75.000000000000369];
smiData.RigidTransform(14).angle = 6.9446174860676438E-17;
smiData.RigidTransform(14).axis = [-0 -0.04059151787866886 0.999175824705695 ...
                                   ];
smiData.RigidTransform(14).ID = 'F[Beam-1:-:Support_N-1]';
smiData.RigidTransform(15).translation = ...
  [-5 -3.5024154589371745 -140];
smiData.RigidTransform(15).angle = 2.0943951023931953;
smiData.RigidTransform(15).axis = [-0.57735026918962584 -0.57735026918962584 ...
                                   0.57735026918962584];
smiData.RigidTransform(15).ID = 'B[Beam-1:-:Support_S-1]';
smiData.RigidTransform(16).translation = ...
  [-5.0000000000000364 1.6115422644174013 -7.1143091417980031E-13];
smiData.RigidTransform(16).angle = 2.0943951023931953;
smiData.RigidTransform(16).axis = [-0.57735026918962573 -0.57735026918962584 ...
                                   0.57735026918962584];
smiData.RigidTransform(16).ID = 'F[Beam-1:-:Support_S-1]';
smiData.RigidTransform(17).translation = ...
  [-2.0000000000000018 -2.5000000000000022 42.499999999999993];
smiData.RigidTransform(17).angle = 2.0943951023931953;
smiData.RigidTransform(17).axis = [-0.57735026918962584 -0.57735026918962584 ...
                                   0.57735026918962584];
smiData.RigidTransform(17).ID = 'B[Support_E-1:-:Support_N-1]';
smiData.RigidTransform(18).translation = ...
  [-36.500000000000014 33.111542264416393 9.99999999999924];
smiData.RigidTransform(18).angle = 2.0943951023931953;
smiData.RigidTransform(18).axis = [-0.57735026918962584 -0.57735026918962562 ...
                                   0.57735026918962584];
smiData.RigidTransform(18).ID = 'F[Support_E-1:-:Support_N-1]';
smiData.RigidTransform(19).translation = ...
  [0 0 -32.500000000000028];
smiData.RigidTransform(19).angle = 3.1415926535897931;
smiData.RigidTransform(19).axis = [1 0 0];
smiData.RigidTransform(19).ID = 'B[Support_E-1:-:Support_S-1]';
smiData.RigidTransform(20).translation = ...
  [-34.500000000000021 35.611542264416357 9.99999999999887];
smiData.RigidTransform(20).angle = 3.1415926535897931;
smiData.RigidTransform(20).axis = [1 -1.0022867662845734E-51 -2.8888949165808538E-34 ...
                                   ];
smiData.RigidTransform(20).ID = 'F[Support_E-1:-:Support_S-1]';
smiData.RigidTransform(21).translation = ...
  [36.500000000000007 33.111542264416535 9.99999999999998];
smiData.RigidTransform(21).angle = 3.1415926535897931;
smiData.RigidTransform(21).axis = [1 0 0];
smiData.RigidTransform(21).ID = 'B[Support_N-1:-:Support_W-1]';
smiData.RigidTransform(22).translation = ...
  [1.9999999999999645 -2.5000000000000231 42.499999999999687];
smiData.RigidTransform(22).angle = 3.1415926535897931;
smiData.RigidTransform(22).axis = [-1 -4.85722573273506E-17 0];
smiData.RigidTransform(22).ID = 'F[Support_N-1:-:Support_W-1]';
smiData.RigidTransform(23).translation = ...
  [0 0 9.99999999999998];
smiData.RigidTransform(23).angle = 0;
smiData.RigidTransform(23).axis = [0 0 0];
smiData.RigidTransform(23).ID = 'B[Support_S-1:-:Support_W-1]';
smiData.RigidTransform(24).translation = ...
  [-34.500000000000014 -35.611542264416528 -32.499999999999979];
smiData.RigidTransform(24).angle = 9.6609653480017E-18;
smiData.RigidTransform(24).axis = [0.71824022278917377 -0.695795215827012 ...
                                   -2.4140245907349339E-18];
smiData.RigidTransform(24).ID = 'F[Support_S-1:-:Support_W-1]';
smiData.Solid = struct;
smiData.Solid(1).mass = 0.035239916555002554;
smiData.Solid(1).CoM = [8.0114333137829753E-5 20.749164369621809 5];
smiData.Solid(1).MoI = [6.4390971940797268 18.710932044533845 24.562697296030194 ...
                        ];
smiData.Solid(1).PoI = [0 0 -6.36863787856876E-5];
smiData.Solid(1).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(1).opacity = 1;
smiData.Solid(1).ID = 'Support_S*:*Default';
smiData.Solid(2).mass = 0.035240000000000014;
smiData.Solid(2).CoM = [0 20.749169960216761 5];
smiData.Solid(2).MoI = [6.4390858390087082 18.711028333333353 24.562780839008731 ...
                        ];
smiData.Solid(2).PoI = [0 0 0];
smiData.Solid(2).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(2).opacity = 1;
smiData.Solid(2).ID = 'Support_N*:*Default';
smiData.Solid(3).mass = 0.0049500000000000013;
smiData.Solid(3).CoM = [0 0 0];
smiData.Solid(3).MoI = [2.2065624999999995 2.186925 0.057862500000000011 ...
                        ];
smiData.Solid(3).PoI = [0 0 0];
smiData.Solid(3).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(3).opacity = 1;
smiData.Solid(3).ID = 'Support_E*:*Default';
smiData.Solid(4).mass = 0.004950000000000003;
smiData.Solid(4).CoM = [0 0 0];
smiData.Solid(4).MoI = [2.2065625 2.1869250000000005 0.057862500000000018 ...
                        ];
smiData.Solid(4).PoI = [0 0 0];
smiData.Solid(4).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(4).opacity = 1;
smiData.Solid(4).ID = 'Support_W*:*Default';
smiData.Solid(5).mass = 0.461701578178441;
smiData.Solid(5).CoM = [0 0 109.39176670477715];
smiData.Solid(5).MoI = [1501.6390470785057 2583.2339432793156 2176.7755962508836 ...
                        ];
smiData.Solid(5).PoI = [0 0 0];
smiData.Solid(5).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(5).opacity = 1;
smiData.Solid(5).ID = 'Base*:*Default';
smiData.Solid(6).mass = 0.029965491720862915;
smiData.Solid(6).CoM = [0 7.5125207279858417 74.999999999999986];
smiData.Solid(6).MoI = [66.045857901150882 49.669392863295961 17.130048349789266 ...
                        ];
smiData.Solid(6).PoI = [0 0 0];
smiData.Solid(6).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(6).opacity = 1;
smiData.Solid(6).ID = 'Shaft*:*Default';
smiData.Solid(7).mass = 0.13092430304202785;
smiData.Solid(7).CoM = [0 0 0];
smiData.Solid(7).MoI = [51.963855877380858 51.963855877380865 51.963855877380858 ...
                        ];
smiData.Solid(7).PoI = [0 0 0];
smiData.Solid(7).color = [0.50196078431372548 0 0];
smiData.Solid(7).opacity = 1;
smiData.Solid(7).ID = 'Ball*:*Default';
smiData.Solid(8).mass = 0.0053920289855072428;
smiData.Solid(8).CoM = [0 0 -70];
smiData.Solid(8).MoI = [8.8396143822969915 8.87067687198067 0.096329901620669733 ...
                        ];
smiData.Solid(8).PoI = [0 0 0];
smiData.Solid(8).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(8).opacity = 1;
smiData.Solid(8).ID = 'Beam*:*Default';
smiData.CylindricalJoint = struct;
smiData.CylindricalJoint.Rz = struct;
smiData.CylindricalJoint.Rz.Pos = -94.502460665329;
smiData.CylindricalJoint.Pz = struct;
smiData.CylindricalJoint.Pz.Pos = 0;
smiData.CylindricalJoint.ID = '[Base-1:-:Shaft-1]';
smiData.PlanarJoint = struct;
smiData.PlanarJoint(1).Rz = struct;
smiData.PlanarJoint(1).Rz.Pos = -9.54166404439055E-15;
smiData.PlanarJoint(1).Px = struct;
smiData.PlanarJoint(1).Px.Pos = 0;
smiData.PlanarJoint(1).Py = struct;
smiData.PlanarJoint(1).Py.Pos = 0;
smiData.PlanarJoint(1).ID = '[Support_E-1:-:Support_S-1]';
smiData.PlanarJoint(2).Rz = struct;
smiData.PlanarJoint(2).Rz.Pos = -9.54166404439055E-15;
smiData.PlanarJoint(2).Px = struct;
smiData.PlanarJoint(2).Px.Pos = 0;
smiData.PlanarJoint(2).Py = struct;
smiData.PlanarJoint(2).Py.Pos = 0;
smiData.PlanarJoint(2).ID = '[Support_S-1:-:Support_W-1]';
smiData.PrismaticJoint = struct;
smiData.PrismaticJoint(1).Pz = struct;
smiData.PrismaticJoint(1).Pz.Pos = 0;
smiData.PrismaticJoint(1).ID = '[Beam-1:-:Support_N-1]';
smiData.PrismaticJoint(2).Pz = struct;
smiData.PrismaticJoint(2).Pz.Pos = 0;
smiData.PrismaticJoint(2).ID = '[Support_N-1:-:Support_W-1]';

