C:\Users\Imad\Desktop\Simon Fraser University\Summer 2021\MSE 312\Designs\Fly Wheel\SolidWorks\Slide-Static 1
C:\Users\Imad\Desktop\Simon Fraser University\Summer 2021\MSE 312\Designs\Fly Wheel\SolidWorks\Slide-Static 1
C:\Users\Imad\Desktop\Simon Fraser University\Summer 2021\MSE 312\Designs\Fly Wheel\SolidWorks\Slide-Static 1
C:\Users\Imad\Desktop\Simon Fraser University\Summer 2021\MSE 312\Designs\Fly Wheel\SolidWorks\Slide-Static 1
C:\Users\Imad\Desktop\Simon Fraser University\Summer 2021\MSE 312\Designs\Fly Wheel\SolidWorks\Slide-Static 1
C:\Users\Imad\Desktop\Simon Fraser University\Summer 2021\MSE 312\Designs\Fly Wheel\SolidWorks\Slide-Static 1
